apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: xdatabases.platform.example.com
  labels:
    provider: aws
    service: rds
spec:
  group: platform.example.com
  names:
    kind: XDatabase
    plural: xdatabases
  claimNames:
    kind: Database
    plural: databases
  connectionSecretKeys:
    - endpoint
    - port
    - username
    - password
    - database
    - connection-string
  versions:
  - name: v1alpha1
    served: true
    referenceable: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties:
              # Environment configuration
              environment:
                type: string
                description: "Environment name (dev, staging, prod)"
                enum: ["dev", "staging", "prod"]
                default: "dev"
              
              # Database engine configuration
              engine:
                type: string
                description: "Database engine"
                enum: ["postgres", "mysql", "mariadb"]
                default: "postgres"
              
              engineVersion:
                type: string
                description: "Database engine version"
                default: "15.4"
              
              # Instance configuration
              instanceClass:
                type: string
                description: "RDS instance class"
                enum: [
                  "db.t3.micro", "db.t3.small", "db.t3.medium", "db.t3.large", "db.t3.xlarge", "db.t3.2xlarge",
                  "db.t4g.micro", "db.t4g.small", "db.t4g.medium", "db.t4g.large", "db.t4g.xlarge", "db.t4g.2xlarge",
                  "db.r5.large", "db.r5.xlarge", "db.r5.2xlarge", "db.r5.4xlarge", "db.r5.8xlarge", "db.r5.12xlarge",
                  "db.r6g.large", "db.r6g.xlarge", "db.r6g.2xlarge", "db.r6g.4xlarge", "db.r6g.8xlarge", "db.r6g.12xlarge"
                ]
                default: "db.t3.micro"
              
              # Storage configuration
              storage:
                type: object
                description: "Storage configuration"
                properties:
                  allocatedStorage:
                    type: integer
                    description: "Allocated storage in GB"
                    minimum: 20
                    maximum: 65536
                    default: 20
                  maxAllocatedStorage:
                    type: integer
                    description: "Maximum allocated storage for autoscaling in GB"
                    minimum: 20
                    maximum: 65536
                  storageType:
                    type: string
                    description: "Storage type"
                    enum: ["gp2", "gp3", "io1", "io2"]
                    default: "gp3"
                  storageEncrypted:
                    type: boolean
                    description: "Enable storage encryption"
                    default: true
                  kmsKeyId:
                    type: string
                    description: "KMS key ID for encryption (optional)"
                  iops:
                    type: integer
                    description: "IOPS for io1/io2 storage types"
                    minimum: 1000
                    maximum: 80000
                  throughput:
                    type: integer
                    description: "Throughput for gp3 storage type (MiB/s)"
                    minimum: 125
                    maximum: 1000
                required:
                  - allocatedStorage
                  - storageType
                  - storageEncrypted
                default:
                  allocatedStorage: 20
                  storageType: "gp3"
                  storageEncrypted: true
              
              # Database configuration
              database:
                type: object
                description: "Database configuration"
                properties:
                  name:
                    type: string
                    description: "Initial database name"
                    pattern: "^[a-zA-Z][a-zA-Z0-9_]*$"
                    minLength: 1
                    maxLength: 63
                    default: "appdb"
                  username:
                    type: string
                    description: "Master username"
                    pattern: "^[a-zA-Z][a-zA-Z0-9_]*$"
                    minLength: 1
                    maxLength: 63
                    default: "dbadmin"
                  port:
                    type: integer
                    description: "Database port"
                    minimum: 1150
                    maximum: 65535
                  parameterGroupName:
                    type: string
                    description: "Custom parameter group name"
                  optionGroupName:
                    type: string
                    description: "Custom option group name"
                required:
                  - name
                  - username
                default:
                  name: "appdb"
                  username: "dbadmin"
              
              # High availability and backup
              availability:
                type: object
                description: "High availability and backup configuration"
                properties:
                  multiAz:
                    type: boolean
                    description: "Enable Multi-AZ deployment"
                    default: false
                  availabilityZone:
                    type: string
                    description: "Preferred availability zone (for single-AZ)"
                  backupRetentionPeriod:
                    type: integer
                    description: "Backup retention period in days"
                    minimum: 0
                    maximum: 35
                    default: 7
                  backupWindow:
                    type: string
                    description: "Backup window (UTC)"
                    pattern: "^([0-1][0-9]|2[0-3]):[0-5][0-9]-([0-1][0-9]|2[0-3]):[0-5][0-9]$"
                    default: "03:00-04:00"
                  maintenanceWindow:
                    type: string
                    description: "Maintenance window (UTC)"
                    pattern: "^(sun|mon|tue|wed|thu|fri|sat):([0-1][0-9]|2[0-3]):[0-5][0-9]-(sun|mon|tue|wed|thu|fri|sat):([0-1][0-9]|2[0-3]):[0-5][0-9]$"
                    default: "sun:04:00-sun:05:00"
                  deleteAutomatedBackups:
                    type: boolean
                    description: "Delete automated backups when instance is deleted"
                    default: true
                  deletionProtection:
                    type: boolean
                    description: "Enable deletion protection"
                    default: true
                  finalSnapshotIdentifier:
                    type: string
                    description: "Final snapshot identifier when deleting"
                  skipFinalSnapshot:
                    type: boolean
                    description: "Skip final snapshot when deleting"
                    default: false
                default:
                  multiAz: false
                  backupRetentionPeriod: 7
                  backupWindow: "03:00-04:00"
                  maintenanceWindow: "sun:04:00-sun:05:00"
                  deleteAutomatedBackups: true
                  deletionProtection: true
                  skipFinalSnapshot: false
              
              # Security configuration
              security:
                type: object
                description: "Security configuration"
                properties:
                  vpcSecurityGroupIds:
                    type: array
                    description: "VPC security group IDs"
                    items:
                      type: string
                  dbSubnetGroupName:
                    type: string
                    description: "DB subnet group name"
                  publiclyAccessible:
                    type: boolean
                    description: "Make database publicly accessible"
                    default: false
                  caCertificateIdentifier:
                    type: string
                    description: "CA certificate identifier"
                    default: "rds-ca-2019"
                  certificateRotationRestart:
                    type: boolean
                    description: "Restart instance for certificate rotation"
                    default: false
                  iamDatabaseAuthenticationEnabled:
                    type: boolean
                    description: "Enable IAM database authentication"
                    default: false
                  monitoringInterval:
                    type: integer
                    description: "Enhanced monitoring interval in seconds"
                    enum: [0, 1, 5, 10, 15, 30, 60]
                    default: 0
                  monitoringRoleArn:
                    type: string
                    description: "Enhanced monitoring role ARN"
                  performanceInsightsEnabled:
                    type: boolean
                    description: "Enable Performance Insights"
                    default: false
                  performanceInsightsRetentionPeriod:
                    type: integer
                    description: "Performance Insights retention period in days"
                    enum: [7, 731]
                    default: 7
                default:
                  publiclyAccessible: false
                  caCertificateIdentifier: "rds-ca-2019"
                  certificateRotationRestart: false
                  iamDatabaseAuthenticationEnabled: false
                  monitoringInterval: 0
                  performanceInsightsEnabled: false
                  performanceInsightsRetentionPeriod: 7
              
              # Networking
              networking:
                type: object
                description: "Networking configuration"
                properties:
                  vpcId:
                    type: string
                    description: "VPC ID where database will be created"
                  subnetIds:
                    type: array
                    description: "Subnet IDs for database subnet group"
                    items:
                      type: string
                    minItems: 2
                  allowedCidrBlocks:
                    type: array
                    description: "CIDR blocks allowed to access database"
                    items:
                      type: string
                      pattern: "^([0-9]{1,3}\\.){3}[0-9]{1,3}/[0-9]{1,2}$"
                    default: []
                  allowedSecurityGroups:
                    type: array
                    description: "Security groups allowed to access database"
                    items:
                      type: string
                    default: []
                default:
                  allowedCidrBlocks: []
                  allowedSecurityGroups: []
              
              # Read replicas
              readReplicas:
                type: object
                description: "Read replica configuration"
                properties:
                  enabled:
                    type: boolean
                    description: "Enable read replicas"
                    default: false
                  count:
                    type: integer
                    description: "Number of read replicas"
                    minimum: 1
                    maximum: 5
                    default: 1
                  instanceClass:
                    type: string
                    description: "Instance class for read replicas"
                  regions:
                    type: array
                    description: "Regions for cross-region read replicas"
                    items:
                      type: string
                    default: []
                default:
                  enabled: false
                  count: 1
                  regions: []
              
              # Environment-specific sizing
              sizing:
                type: object
                description: "Environment-specific sizing presets"
                properties:
                  preset:
                    type: string
                    description: "Sizing preset"
                    enum: ["micro", "small", "medium", "large", "xlarge"]
                    default: "micro"
                default:
                  preset: "micro"
              
              # Tags
              tags:
                type: object
                description: "Additional tags for AWS resources"
                additionalProperties:
                  type: string
                default: {}
              
              # Region
              region:
                type: string
                description: "AWS region"
                default: "us-west-2"
            
            required:
              - engine
              - storage
              - database
              - availability
            
            # Default values for the entire spec
            default:
              environment: "dev"
              engine: "postgres"
              engineVersion: "15.4"
              instanceClass: "db.t3.micro"
              storage:
                allocatedStorage: 20
                storageType: "gp3"
                storageEncrypted: true
              database:
                name: "appdb"
                username: "dbadmin"
              availability:
                multiAz: false
                backupRetentionPeriod: 7
                deletionProtection: true
              security:
                publiclyAccessible: false
                iamDatabaseAuthenticationEnabled: false
              readReplicas:
                enabled: false
              sizing:
                preset: "micro"
              region: "us-west-2"
          
          status:
            type: object
            properties:
              # Database instance status
              dbInstanceStatus:
                type: string
                description: "RDS instance status"
              endpoint:
                type: string
                description: "Database endpoint"
              port:
                type: integer
                description: "Database port"
              
              # Connection information
              connectionSecret:
                type: object
                properties:
                  name:
                    type: string
                  namespace:
                    type: string
              
              # Backup information
              latestBackup:
                type: object
                properties:
                  snapshotId:
                    type: string
                  createdAt:
                    type: string
                    format: date-time
              
              # Read replicas status
              readReplicasStatus:
                type: array
                items:
                  type: object
                  properties:
                    identifier:
                      type: string
                    status:
                      type: string
                    endpoint:
                      type: string
                    region:
                      type: string
              
              # Monitoring
              monitoring:
                type: object
                properties:
                  performanceInsights:
                    type: boolean
                  enhancedMonitoring:
                    type: boolean
              
              # Overall conditions
              conditions:
                type: array
                items:
                  type: object
                  properties:
                    type:
                      type: string
                    status:
                      type: string
                    lastTransitionTime:
                      type: string
                      format: date-time
                    reason:
                      type: string
                    message:
                      type: string
    additionalPrinterColumns:
    - name: Environment
      type: string
      jsonPath: .spec.environment
    - name: Engine
      type: string
      jsonPath: .spec.engine
    - name: Version
      type: string
      jsonPath: .spec.engineVersion
    - name: Instance
      type: string
      jsonPath: .spec.instanceClass
    - name: Storage
      type: string
      jsonPath: .spec.storage.allocatedStorage
    - name: Multi-AZ
      type: boolean
      jsonPath: .spec.availability.multiAz
    - name: Status
      type: string
      jsonPath: .status.dbInstanceStatus
    - name: Endpoint
      type: string
      jsonPath: .status.endpoint
    - name: Age
      type: date
      jsonPath: .metadata.creationTimestamp